package com.wsria.demo.entity.jstree;

// Generated 2010-7-30 22:32:17 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ToStringBuilder;

import com.wsria.arch.util.orm.IdEntity;


/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city")
public class City extends IdEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String cityName;
	private Long superId = -1l;
	private String remark;

	public City() {
	}

	public City(String cityName, Long superId) {
		this.cityName = cityName;
		this.superId = superId;
	}

	public City(String cityName, Long superId, String remark) {
		this.cityName = cityName;
		this.superId = superId;
		this.remark = remark;
	}

	@Column(name = "CITY_NAME", nullable = false, length = 20)
	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	@Column(name = "SUPER_ID", nullable = false)
	public Long getSuperId() {
		return this.superId;
	}

	public void setSuperId(Long superId) {
		this.superId = superId;
	}

	@Column(name = "REMARK")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}
}
